### ISSUE TITLE
Task interface

### ISSUE THREAD

**Issue by Pospelove** [ianpatt/sfse#14]
Do you plan to add a Task interface like in SKSE?

**Comment by ianpatt** [comment]
Yes.

**Comment by TommInfinite** [comment]
@ianpatt hi!
Are you planning to add permanent tasks like for F4SE?(https://github.com/TommInfinite/f4se/commit/6597659cd73cc45da4e995578a2b6e7cf569ff0e)

**Comment by ianpatt** [comment]
Implemented in cc05feba0b7afab4882fbc94ecc74079af649cda
