### ISSUE TITLE
Modder/Developer docs?

### ISSUE THREAD

**Issue by jwvanderbeck** [ianpatt/sfse#16]
Hello,

Maybe this is more obvious to those who come from older Bethesda games, but is there any documentation for those of us who want to write plugins using SFSE, any API docs on what we can twiddle with etc?

**Comment by ianpatt** [comment]
The raw plugin API is documented in sfse/PluginAPI.h. SFSE has its own game API, but there's a more friendly-to-use library in development here: https://github.com/Starfield-Reverse-Engineering/CommonLibSF that will probably be more useful to you.
