### ISSUE TITLE
Suggestion: Allow setting working directory `runtimeDir` via flag (SFSE doesn't work with Vortex for me)

### ISSUE THREAD

**Issue by GavinRay97** [ianpatt/sfse#17]
SFSE does not launch properly through Vortex for me, when Starfield is installed on an external SSD.

I have `sfse_loader.exe` at `D:\SteamLibrary\steamapps\common\Starfield`, and it's a symlink to:
`C:\Users\rayga\AppData\Roaming\Vortex\starfield\mods\SFSE-106-0-1-2-1694730447\sfse_loader.exe`

I've tried setting `Start In:` to `D:\SteamLibrary\steamapps\common\Starfield` but it doesn't work.
I get an error popup: `Couldn't find Starfield.exe`
```
SFSE loader: initialize (version = 0.1.2 010701D0 2023-09-23 21:06:31, os = 6.2 (9200))
config path = C:\Users\rayga\AppData\Roaming\Vortex\starfield\mods\SFSE-106-0-1-2-1694730447\Data\SFSE\sfse.ini
procPath = C:\Users\rayga\AppData\Roaming\Vortex\starfield\mods\SFSE-106-0-1-2-1694730447\Starfield.exe
```

However, if I run sfse_loader.exe from a shell in `D:\SteamLibrary\steamapps\common\Starfield`, then it launches fine and prints:
```
D:\SteamLibrary\steamapps\common\Starfield>sfse_loader.exe
SFSE loader: initialize (version = 0.1.2 010701D0 2023-09-23 19:54:45, os = 6.2 (9200))
config path = D:\SteamLibrary\steamapps\common\Starfield\Data\SFSE\sfse.ini
procPath = D:\SteamLibrary\steamapps\common\Starfield\Starfield.exe
launching: Starfield.exe (D:\SteamLibrary\steamapps\common\Starfield\Starfield.exe)
```

By using the `-altexe` flag, I can get a little further, but it doesn't find the rest of the mods:
- ![image](https://github.com/ianpatt/sfse/assets/26604994/31fbff9e-386e-471b-9e82-0eab546d909e)

I'm assuming this is due to the working path used by the loader library, and it incorrectly using `AppData\Roaming\Vortex`
I'd imagine it's related to:
https://github.com/ianpatt/sfse/blob/8c4af406ed86baf69af676132fea337621084ae3/sfse_loader/main.cpp#L87-L88

Below is my Vortex SFSE config:
![image](https://github.com/ianpatt/sfse/assets/26604994/998b7224-5010-4ec9-b67a-9c66e931084d)

**Comment by ianpatt** [comment]
This is intended behavior. People not being able to get the current working directory correct are much more common than people doing silly things with symlinks. Install SFSE correctly; do not use symlinks.

**Comment by GavinRay97** [comment]
Just an FYI, the symlinks are a default behavior when installing with Vortex, so you might get more people reporting this 🤷

**Comment by ianpatt** [comment]
Hoo boy, that's going to cause problems with several DLL plugins. Symlink installation only makes sense for raw data, not things that are going to go through the PE loader.

**Comment by GavinRay97** [comment]
Yeah, not saying it's a _reasonable_ default in this instance, just that it _happens_ to be, unfortunately.

Maybe worth adding a footnote in the Vortex mod description about:
> _"Hey, if this happens, try running `sfse_loader.exe` from the Starfield directory in a shell manually."_

**Comment by ianpatt** [comment]
The mod managers are trying some crazy things out for Starfield. It's going to be a mess until Bethesda shows how things are intended to work and (hopefully) everything settles down. Of course, if BGS wants mods in My Documents, it's going to be war.

**Comment by shinji257** [comment]
I know this ticket is closed but just wanted to drop and say that sfse works fine with Vortex and sfse installed via the mod manager normally.  It might be because I'm using hardlinks rather than symlinks.  Just an FYI.
