### ISSUE TITLE
When do you plan to respect addressIndependence?

### ISSUE THREAD

**Issue by igromanru** [ianpatt/sfse#19]
Hello there, my mod uses pattern scan to find the right address to patch. So far the pattern worked over all updates and if it stops working, nothing will be patched, no harm done.   
https://github.com/igromanru/SF-Zero-Weight/blob/main/Plugin/src/main.cpp#L47
Therefore it would be very appreciated, if SFSE would start checking for the `addressIndependence` flag, so I don't have to add `compatibleVersions` for each game version.   
I could make a Pull Request, but before I do any work, I wanted to ask what are the plans for it. 
Best Regards
Igromanru

**Comment by dczeiner** [comment]
afaik it's already working with the latest version.
at least I can confirm my plugin for Starfield.exe Auto-backup didn't need an update in order to work with the latest SFSE.

**Comment by igromanru** [comment]
Indeed, my bad. I still had code from yesterday.  
Here is it now.  
https://github.com/ianpatt/sfse/blob/master/sfse/PluginManager.cpp#L493  
Thanks for adding it.
