### ISSUE TITLE
starfield could not be found

### ISSUE THREAD

**Issue by nicholas1795** [ianpatt/sfse#20]
i am running on a steam deck on linux and i placed the files where the description said to on nexus https://www.nexusmods.com/starfield/mods/106
but i keep getting an error saying it could not find starfield.exe 
https://ibb.co/CzxfhGg
https://ibb.co/TcTPppn
these are to show the file path my steam deck downloads the game to automatically and to show that the files are together, im not sure how to edit the sfse to have the correct path, is there a way to do that on my end or would somone else have to fix it

**Comment by ianpatt** [comment]
Github is not for end-user support. I also can't provide tech support for running in an emulated environment.
