### ISSUE TITLE
Regularly getting hook error with latest SFSE

### ISSUE THREAD

**Issue by monster-cookie** [ianpatt/sfse#25]
main.cpp:SetupModMenu:246> ImGuiInjector Version: 1.2.12
main.cpp:SetupModMenu:253> Settings Loaded
main.cpp:SetupModMenu:267> Hook GetRawInputData: 00007FFA4441DE40
main.cpp:SetupModMenu:276> Hook ClipCursor: 00007FFA4441D770
main.cpp:SetupModMenu:282> Hook CreateDXGIFactory2: 00007FFA0CBB43E0
main.cpp:SetupModMenu:289> ImGui one time init completed!
main.cpp:SetupModMenu:293> RegisterInternalPlugin
main.cpp:SetupModMenu:297> Console setup
main.cpp:operator ():312> SFSE PostPostLoad callback message dispatched
main.cpp:FAKE_CreateDXGIFactory2:193> Factory: 000001D7C3F6A450
main.cpp:FAKE_CreateDXGIFactory2:223> Hooked CreateSwapChainForHwnd
main.cpp:FAKE_CreateDXGIFactory2:193> Factory: 000001D7C3F6C8E0
main.cpp:FAKE_CreateDXGIFactory2:193> Factory: 000001D7BF564CA0
main.cpp:FAKE_CreateSwapChainForHwnd:153> Factory: 000001D7C3F6C8E0, Device: 000001E37747D7B0, HWND: 0000000000321292, SwapChain: 000001E3F728E970, Owner: 00000021AA7FE8D8, Ret: 0
main.cpp:FAKE_CreateSwapChainForHwnd:161> Queues[1] = { 000001E37747D7B0, 000001E3F728E970 }
!!! ASSERTION FAILURE !!!
In file     'hook_api.cpp'
In function 'HookFunction'
On line     '17'
Message:    ' false && "minhook failed to hook function"'

Above is from debuglog.txt

Seems to be SFSE itself get it with only it an no other plugins (Not even address lib or plugins enabler) sometimes is every 5 launches or so but today its 100% which finally allowed me to trace down the source the message box that pops up has no title or anything and just this below in the body

!!! ASSERTION FAILURE !!!
In file     'hook_api.cpp'
In function 'HookFunction'
On line     '17'
Message:    ' false && "minhook failed to hook function"'

**Comment by ianpatt** [comment]
This is not from SFSE. It is from a different mod you have installed. Once you have identified the mod that is causing the problem, please request that the author clearly label the source of their error messages.
