### ISSUE TITLE
Tag `v0.2.3`'s commit: `address/version update for 1.9.67`' doesn't exist in a branch (master or otherwise).

### ISSUE THREAD

**Issue by Synthlight** [ianpatt/sfse#26]
https://github.com/ianpatt/sfse/commit/b7aaeee5b7caa5e4eb78de833b3b62870bb78226

![image](https://github.com/ianpatt/sfse/assets/1075166/50ce4bfc-b206-40ed-a52e-c0e96325c52f)

I went to pull master to update my plugins but the commit isn't on a branch so....
I might be able to work around it by checking out the tag but I assume this is an unintentional oversight.

**Comment by ianpatt** [comment]
Only pushed the tag I think. Fixed, thanks.
