### ISSUE TITLE
SKSE referenced in readme (and thanks).

### ISSUE THREAD

**Issue by Chase-san** [ianpatt/sfse#3]
Specifically here:

https://github.com/ianpatt/sfse/blob/d5335775f677b4a7dc54de89449b21de494419cd/sfse_readme.txt#L27C19-L27C19

This is of course largely irrelevant. However I wanted to say: Thanks for all your hard work over the years. I look forward to SFSE.

**Comment by ianpatt** [comment]
Oops, thanks for letting me know.
