### ISSUE TITLE
New Game Update

### ISSUE THREAD

**Issue by Flaine01** [ianpatt/sfse#30]
Starfield game update 1_11_36 makes SFSE no longer work
![SFSEnolongerworks](https://github.com/ianpatt/sfse/assets/112411212/7bbe9d68-133b-4a94-bde5-ca9bca707fbc)

**Comment by nr275** [comment]
Not an issue, read the error message it says exactly why it won't start.

**Comment by ianpatt** [comment]
17f0d296162950751db3b38ced2935ba992ccba1
This is not a bug. Please do not report new game versions here.
