### ISSUE TITLE
micro-stutter when using sfse on linux using proton

### ISSUE THREAD

**Issue by Xenophobe-01** [ianpatt/sfse#31]
ISSUE
Launching the game with sfse_loader.exe causes micro-stuttering in the game, it's not constant but it is frequent. The micro-stutter is more noticeable using steam's proton 9.0-1 and Experimental, it's less noticeable with GE-Proton9-6. If I launch the game normally it's smooth. 

SYSTEM INFO
Linux Mint 21.3, Kernel Version: 6.5.0-35-generic
Intel i7-11700K
32GB DDR4 at 3200
RX 6950 XT, Mesa 24.1.0 - kisak-mesa PPA
2TB NVMe Gen4x4 SSD

Steam Beta Branch:  Steam Beta Update
Steam Version:  1717294964
Steam Client Build Date:  Sat, Jun 1 5:52 PM UTC -05:00
Steam Web Build Date:  Fri, May 31 9:51 PM UTC -05:00
Steam API Version:  SteamClient021

Steam Proton 9.0-1
Steam Proton Experimental
GE-Proton9-6

LAUNCH OPTIONS USED
bash -c 'exec "${@/Starfield.exe/sfse_loader.exe}" ' gamemoderun %command%

the bash -c 'exec "${@/Starfield.exe/sfse_loader.exe}" '  portion let's sfse launch using the game shortcut in steam

------------------------------------------------------------------------------------------------------------

The micro-stutter is not game breaking, but it is a minor visual bother. Just hoping there's a simple tweak to make it smooth, like the script extender is in other games.

**Comment by ianpatt** [comment]
Empty Data/SFSE/Plugins and try again.

**Comment by Xenophobe-01** [comment]
Final mod updated, tested the SFSE 0.2.8 for an hour of game play, the stutter is gone now.  Thanks for being a dedicated developer.
