### ISSUE TITLE
Ctd

### ISSUE THREAD

**Issue by RoeYasha** [ianpatt/sfse#38]
Version 0.2.12 ctd when save game

**Comment by ianpatt** [comment]
Attach a Trainwreck log. SFSE currently doesn't do anything when saving the game.

**Comment by RoeYasha** [comment]
[2024-09-01-11-20-15.log](https://github.com/user-attachments/files/16827280/2024-09-01-11-20-15.log)

This is the log

**Comment by ianpatt** [comment]
As you can see from the log, SFSE is not in the stack at the time of the crash. This is extremely unlikely to be related to anything that we are doing.

**Comment by RoeYasha** [comment]
but when i didnt use sfse, load and save is normal
