### ISSUE TITLE
readme reference dll and exe, location not found

### ISSUE THREAD

**Issue by TooSlow2Care** [ianpatt/sfse#4]
Firstly, thank you for your efforts with all of the BSW titles!
Reviewing the readme file it is referenced to '1. Copy the dll and exe files into your Starfield folder.'   I am not finding these files anywhere within the SFSE repository.
Please help an old boomer/mechanical engineer wrap his head around Git and some software step I must be missing.

Cheers

**Comment by ianpatt** [comment]
The github page is for programmers, not for end users. Most people should download from https://www.nexusmods.com/starfield/mods/106.
