### ISSUE TITLE
sfse_loadder.exe wont start up game

### ISSUE THREAD

**Issue by Dark-Dominion** [ianpatt/sfse#5]
Hello,

Starfield Steam version.
Placed the .exe and the .dll in the Starfield root folder ( where starfield.exe is ).
Launched the game through the sfse_loader.exe but the game doesn't load.
The small cmd box appears but then it disappears without starting the game

[sfse.txt](https://github.com/ianpatt/sfse/files/12516698/sfse.txt)
[sfse_loader.txt](https://github.com/ianpatt/sfse/files/12516699/sfse_loader.txt)

What am I doing wrong ?

**Comment by ianpatt** [comment]
This is for programmers/development, not technical support.
